### ISSUE TITLE
Could not load file or assembly 'netstandard, Version=2.1.0.0

### ISSUE THREAD

**Issue by azizahmed45** [fzany/3CXCallControlAPI_v16#2]
`System.IO.FileLoadException: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken="token"'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
File name: 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=token' ---> System.IO.FileLoadException: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken="token'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
   at System.AppDomain.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
   at OMSamples.Program.Bootstrap(String[] args)
   at OMSamples.Program.Main(String[] args) in C:\Users\Aziz\source\repos\3CXCallControlAPI_v16\OMSamples\Program.cs:line 93`

**Comment by olorunfemidavis** [comment]
I believe you have solved the issue @azizahmed45

**Comment by azizahmed45** [comment]
Yes
I missed the closed issue.
Should I create a poll request with the version update?

**Comment by olorunfemidavis** [comment]
Sure you can.
