### ISSUE TITLE
error on ActiveConnections.cs:line 148

### ISSUE THREAD

**Issue by Pastis67** [fzany/3CXCallControlAPI_v16#6]
Hello, I  got this error with latest V16 version...
OMSamplesCore.exe connection makecall 45 46
give me :
Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at TCX.Configuration.PhoneSystem.MakeCall(RegistrarRecord from_device, String destination)
   at OMSamples.Samples.ActiveConnections.Run(String[] args) in C:\Users\admin\Downloads\3CXCallControlAPI_v16-master\3CXCallControlAPI_v16-master\OMSamples\Samples\ActiveConnections.cs:line 148
   at OMSamples.SampleStarter.StartSample(String[] args) in C:\Users\admin\Downloads\3CXCallControlAPI_v16-master\3CXCallControlAPI_v16-master\OMSamples\SampleStarter.cs:line 98
anyone has a clue ?
thanks..

**Comment by olorunfemidavis** [comment]
Was there an active connection?

**Comment by olorunfemidavis** [comment]
You can also confirm if RegistrarRecord from_device and String destination is not null.

**Comment by Pastis67** [comment]
hello there was no active connection...
what do you mean by "not full" ? :(

**Comment by olorunfemidavis** [comment]
You need an active connection in order to use the Make call API. 
However, there are 2 other options. 

Passing null (empty/ uninitialized) data to 3cX will throw an error.
